### ISSUE TITLE
Docker file needs 'apt-get clean' at start

### ISSUE THREAD

**Issue by mcpeak** [groupon/codeburner#22]
I was attempting to deploy with the docker-build script and kept receiving an error about failing to retrieve specific dependencies.  This is likely due to an old base layer docker image and updated dependencies.

Adding 'apt-get clean' to the beginning of the Dockerfile allowed me to successfully complete the Docker deployment.

**Comment by 10dot** [comment]
I added this to the PR going out today;  thanks for the submission!
